name: merge to main workflow
on:
  push:
    branches: [main]

jobs:
  get_asdf_version:
    runs-on: ubuntu-22.04
    outputs:
      asdf_version: '${{ steps.asdf-version.outputs.version }}'
      tag_format: '${{ steps.load-config.outputs.TAG_FORMAT }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Get asdf version
        id: asdf-version
        run: >-
          echo "version=$(awk '!/^#/ && NF {print $1; exit}'
          .tool-versions.asdf)" >> "$GITHUB_OUTPUT"
      - name: Load config value
        id: load-config
        run: |
          TAG_FORMAT=$(yq '.TAG_FORMAT' .github/config/settings.yml)
          echo "TAG_FORMAT=$TAG_FORMAT" >> "$GITHUB_OUTPUT"
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@5ccebbf821beef2de6abdce9e392b3cbeb4999e3
    needs:
      - get_asdf_version
    with:
      asdfVersion: '${{ needs.get_asdf_version.outputs.asdf_version }}'
    secrets:
      SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
  tag_release:
    needs: [quality_checks, get_asdf_version]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@997a1946c83bb2a9eda418847ed640738af949ff
    with:
      dry_run: true
      asdfVersion: ${{ needs.get_asdf_version.outputs.asdf_version }}
      branch_name: main
      tag_format: ${{ needs.get_asdf_version.outputs.tag_format }}
    secrets: inherit
  build_all_images:
    needs: tag_release
    uses: ./.github/workflows/build_all_images.yml 
    with: 
      docker_tag: '${{ needs.tag_release.outputs.version_tag }}'
      tag_latest: false
