name: "Delete old images"

# Controls when the action will run - in this case triggered manually and on schedule
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,13 * * *"
  push:
    branches: [main]

jobs:
  delete-old-pushed-images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout local code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      - name: delete unused images
        shell: bash
        run: .github/scripts/delete_unused_images.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
