name: pull_request
'on':
  pull_request:
    branches:
      - main
env:
  BRANCH_NAME: '${{ github.event.pull_request.head.ref }}'
jobs:
  dependabot-auto-approve-and-merge:
    needs: quality_checks
    uses: >-
      NHSDigital/eps-common-workflows/.github/workflows/dependabot-auto-approve-and-merge.yml@5ccebbf821beef2de6abdce9e392b3cbeb4999e3
    secrets:
      AUTOMERGE_APP_ID: '${{ secrets.AUTOMERGE_APP_ID }}'
      AUTOMERGE_PEM: '${{ secrets.AUTOMERGE_PEM }}'
  get_asdf_version:
    runs-on: ubuntu-22.04
    outputs:
      asdf_version: '${{ steps.asdf-version.outputs.version }}'
      tag_format: '${{ steps.load-config.outputs.TAG_FORMAT }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Get asdf version
        id: asdf-version
        run: >-
          echo "version=$(awk '!/^#/ && NF {print $1; exit}'
          .tool-versions.asdf)" >> "$GITHUB_OUTPUT"
      - name: Load config value
        id: load-config
        run: |
          TAG_FORMAT=$(yq '.TAG_FORMAT' .github/config/settings.yml)
          echo "TAG_FORMAT=$TAG_FORMAT" >> "$GITHUB_OUTPUT"
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@5ccebbf821beef2de6abdce9e392b3cbeb4999e3
    needs:
      - get_asdf_version
    with:
      asdfVersion: '${{ needs.get_asdf_version.outputs.asdf_version }}'
    secrets:
      SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
  pr_title_format_check:
    uses: >-
      NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@5ccebbf821beef2de6abdce9e392b3cbeb4999e3
  get_issue_number:
    runs-on: ubuntu-22.04
    needs: quality_checks
    outputs:
      issue_number: '${{ steps.get_issue_number.outputs.result }}'
      version: '${{ steps.get_issue_number.outputs.version_number }}'
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        name: get issue number
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: '${{ steps.commit_id.outputs.commit_id }}'
      sha_short: '${{ steps.commit_id.outputs.sha_short }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          ref: '${{ env.BRANCH_NAME }}'
      - name: Get Commit ID
        id: commit_id
        run: |
          #  echo "commit_id=${{ github.sha }}" >> "$GITHUB_ENV"
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
  build_all_images:
    needs:
      - get_issue_number
      - get_commit_id
    uses: ./.github/workflows/build_all_images.yml 
    with: 
      docker_tag: 'pr-${{ needs.get_issue_number.outputs.issue_number }}-${{ needs.get_commit_id.outputs.sha_short }}'
      tag_latest: false
      push_image: false
