name: release workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4"

jobs:
  get_config_values:
    runs-on: ubuntu-22.04
    outputs:
      devcontainer_image_name: ${{ steps.load-config.outputs.DEVCONTAINER_IMAGE_NAME }}
      devcontainer_image_version: ${{ steps.load-config.outputs.DEVCONTAINER_IMAGE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Load config value
        id: load-config
        run: |
          DEVCONTAINER_IMAGE_NAME=$(jq -r '.build.args.IMAGE_NAME' .devcontainer/devcontainer.json)
          DEVCONTAINER_IMAGE_VERSION=$(jq -r '.build.args.IMAGE_VERSION' .devcontainer/devcontainer.json)
          echo "DEVCONTAINER_IMAGE_NAME=$DEVCONTAINER_IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "DEVCONTAINER_IMAGE_VERSION=$DEVCONTAINER_IMAGE_VERSION" >> "$GITHUB_OUTPUT"
  get_asdf_version:
    runs-on: ubuntu-22.04
    outputs:
      asdf_version: '${{ steps.asdf-version.outputs.version }}'
      tag_format: '${{ steps.load-config.outputs.TAG_FORMAT }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Get asdf version
        id: asdf-version
        run: >-
          echo "version=$(awk '!/^#/ && NF {print $1; exit}'
          .tool-versions.asdf)" >> "$GITHUB_OUTPUT"
      - name: Load config value
        id: load-config
        run: |
          TAG_FORMAT=$(yq '.TAG_FORMAT' .github/config/settings.yml)
          echo "TAG_FORMAT=$TAG_FORMAT" >> "$GITHUB_OUTPUT"
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@997a1946c83bb2a9eda418847ed640738af949ff
    needs:
      - get_asdf_version
    with:
      asdfVersion: '${{ needs.get_asdf_version.outputs.asdf_version }}'
    secrets:
      SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
  tag_release:
    needs: [quality_checks, get_asdf_version]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@997a1946c83bb2a9eda418847ed640738af949ff
    with:
      dry_run: false
      asdfVersion: ${{ needs.get_asdf_version.outputs.asdf_version }}
      branch_name: main
      tag_format: ${{ needs.get_asdf_version.outputs.tag_format }}
    secrets: inherit
  build_all_images:
    needs: 
      - tag_release
      - get_config_values
    uses: ./.github/workflows/build_all_images.yml 
    with: 
      docker_tag: '${{ needs.tag_release.outputs.version_tag }}'
      tag_latest: true
      NO_CACHE: true
      runtime_docker_image: "${{ needs.get_config_values.outputs.devcontainer_image_name }}:githubactions-${{ needs.get_config_values.outputs.devcontainer_image_version }}"
